"""add chunk embeddings for hybrid retrieval

Revision ID: cde7e41980da
Revises: 6f50037b5b20
Create Date: 2026-08-01 16:30:42.557764
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cde7e41980da"
down_revision: str | None = "6f50037b5b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("document_chunk_id", sa.String(length=36), nullable=False),
        sa.Column("provider_name", sa.String(length=80), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_chunk_id"], ["document_chunks.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunk_embeddings_document_chunk_id"),
        "chunk_embeddings",
        ["document_chunk_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_chunk_embeddings_workspace_id"), "chunk_embeddings", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_embeddings_workspace_id"), table_name="chunk_embeddings")
    op.drop_index(op.f("ix_chunk_embeddings_document_chunk_id"), table_name="chunk_embeddings")
    op.drop_table("chunk_embeddings")
    # ### end Alembic commands ###
